// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    'HelloWorld.story': typeof import('./components/HelloWorld.story.vue')['default']
    ILogosTailwindcssIcon: typeof import('~icons/logos/tailwindcss-icon')['default']
    ILogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default']
    ILogosVitejs: typeof import('~icons/logos/vitejs')['default']
    ILogosVitest: typeof import('~icons/logos/vitest')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
    ILogosVueuse: typeof import('~icons/logos/vueuse')['default']
    Link: typeof import('./components/Link.vue')['default']
    'Link.story': typeof import('./components/Link.story.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
